### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by danse** [usagi/cinnamonroll#4]
Hi, i am curious about what this is, and specifically, how it compares to [Clay](https://github.com/sebastiaanvisser/clay).

Having a look around, it seems to me that with this tool you are just converting CSS to and from a different syntax that you like more, that you named _cinnamon_. Is there anything more i am missing?

Could you elaborate a bit on this? Thanks!

**Comment by usagi** [comment]
This project is a thing of the old days more than four years. At that time, I was need for CSS preprocessor for the web site description myself. Then, cinnamonroll was developed with Haskell. But, I'm busy the other tasks, I can not maintain the cinnamonroll for now.

This code is MIT license. You can use free if you think useful for it or a part of codes. Thanks.

**Comment by danse** [comment]
Aha, i didn't notice the old commit dates! Alright, thanks for the explanation!
